---
title: "p8105_hw5_ww2579"
author: "Wenzhao Wu"
date: "11/10/2020"
output: github_document
---

```{r setup}
library(tidyverse)

knitr::opts_chunk$set(
  fig.width = 12,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

## Problem 1

Read in the data. 

```{r}
homicide_df = 
  read_csv("./homicide_data.csv") %>%
  mutate(
    city_state = str_c(city, state, sep = "_"),
    resolved = case_when(
      disposition == "Closed without arrest" ~ "unsolved",
      disposition == "Open/No arrest" ~ "unsolved",
      disposition == "Closed by arrest" ~ "solved")
  ) %>%
  select(city_state, resolved)
```

Let's look at this a bit

```{r}
aggregate_df = homicide_df %>%
  group_by(city_state) %>%
  summarize(
    hom_total = n(),
    hom_unsolved = sum(resolved == "unsolved")
  )
```

Can I do a prop test for a single city?

```{r}
prop.test(
  aggregate_df %>% filter(city_state == "Baltimore_MD") %>% pull(hom_unsolved),
  aggregate_df %>% filter(city_state == "Baltimore_MD") %>% pull (hom_total)) %>%
  broom::tidy()
```

Try to iterate

```{r}
results_df = 
  aggregate_df %>%
  mutate(
    prop_tests = map2(.x = hom_unsolved, .y = hom_total, ~prop.test(x = .x, n = .y)), 
    tidy_tests = map(.x = prop_tests, ~broom::tidy(.x))
 ) %>%
  select(-prop_tests) %>%
  unnest(tidy_tests) %>%
  select(city_state, estimate, conf.low, conf.high)
```

## Problem 2

Tidy and iterate over all csv files

```{r}
tidy = function(y) {
  pivot_longer(
    data = y,
    week_1:week_8,
    names_to = "week",
    values_to = "value",
    names_prefix = "week_") %>%
  mutate(
    week = as.factor(week))
}

path_df = 
  tibble(
  path = list.files("./lda_data")
) %>%
  mutate(path = str_c("lda_data/", path),
         data = map(.x = path, ~read_csv(.x)),
         tidied = map(.x = data, ~tidy(.x)))



```

